### ISSUE TITLE
Stuck trying to reg with apple and not reciving validation data 

### ISSUE THREAD

**Issue by cameronaaron** [TaeHagen/bluebubbles-app#10]
the app keeps going into a state where it no longer seems to be registered with imessage. Manuelly trying to rereg in the settings causes it to throw an exception PanicException(called 'Result::unwrap()' on an 'Err value: SendError {..})

trying to send messages resutls in the same exception. the validation relay seems to have the same code and be doing ok the logs just show it sent out validation data

**Comment by cameronaaron** [comment]
Screenshot and logs sent to copperboy

**Comment by TaeHagen** [comment]
Fixed pending release
