### ISSUE TITLE
When restoring settings using a blue bubbles local backup file it causes open bubbles to go crazy thinking it cannot connect to a server and eventually causes rereg to crash

### ISSUE THREAD

**Issue by cameronaaron** [TaeHagen/bluebubbles-app#12]
When restoring settings using a blue bubbles local backup file it causes open bubbles to go crazy thinking it cannot connect to a server and eventually causes rereg to crash. It also causes the top part of the app to show a puling red thing akin to in blue bubbles when in blue bubbles it cannot connect to the server

**Comment by TaeHagen** [comment]
Intentional behavior, restoring BlueBubbles setting backups are not supported.
