### ISSUE TITLE
Enhancements to redacted mode

### ISSUE THREAD

**Issue by CloudRealm** [TaeHagen/bluebubbles-app#14]
- Make redacted mode apply to all personally identifying things in iMessage profile specially in the starts chat using section
- Change wording of alias, to say something like redacted phone number or redacted email instead of just alias
- Make redacted mode also apply to my Mac / my device section (side note maybe change it to say my device instead of my Mac in unredacted mode)

**Comment by cameronaaron** [comment]
@TaeHagen fufilled in https://github.com/TaeHagen/bluebubbles-app/commit/78f70b1bbb53289b46cfe6b74014fc940f61d005 right

**Comment by CloudRealm** [comment]
![Screenshot_20240827-152354](https://github.com/user-attachments/assets/8fe26507-6040-4ebb-bca2-a3996e3acd24)
If show chat name as placeholder is enabled, then this shows in redacted mode at least for group chats

I suggest this option be turned off whenever redacted mode is toggled
