### ISSUE TITLE
App doesn't sync old messages and doesn't receive new messages.

### ISSUE THREAD

**Issue by khangvttran** [TaeHagen/bluebubbles-app#17]
Finished setting up but my old chats do not sync and I'm not getting any new messages.

New update: starting to get iMessages too, is there a way to sync older msgs?

Update: I'm able to receive forwarded SMS msgs but no iMessages yet

**Comment by TaeHagen** [comment]
No way to sync older messages. Please ask discord for help before filing a bug.
