### ISSUE TITLE
Not downloading/receiving images

### ISSUE THREAD

**Issue by EJAflatminor** [TaeHagen/bluebubbles-app#18]
When someone sends me an image through iMessage (group or 1-to-1 chat), I see the loading icon for an image saying "Downloading Image" with a progress bar. Once the progress bar finishes, it displays "Failed to Download! Tap to try again". The same problem repeats when I click try again. I haven't checked if this also occurs with videos yet.

A video with the issue: https://github.com/user-attachments/assets/5e0a4256-82e4-48d0-94a8-771fa166aef7

**Comment by longwolfdude** [comment]
The same thing happens to me. I thought I was the only one.![Screenshot_20240821_194049_OpenBubbles.png](https://github.com/user-attachments/assets/92372234-f13f-420e-abf7-c2506878a533)

I keep getting this error when I try to send Images

**Comment by EJAflatminor** [comment]
Seems to be fixed in latest update.
