### ISSUE TITLE
Voice Messages - Not being properly displayed 

### ISSUE THREAD

**Issue by CloudRealm** [TaeHagen/bluebubbles-app#19]
Voice Messages do not show like they are in blue bubbles

They currently look like this 
![Screenshot_20240825-234720](https://github.com/user-attachments/assets/bf9a1250-4946-4a54-b46a-0304844187f6)
![Screenshot_20240826-011533](https://github.com/user-attachments/assets/76969c65-ae83-4536-9101-01636f6c0dab)

**Comment by fl3xtra** [comment]
https://github.com/Schaback/CafRedirector/releases/tag/v1.1

**Comment by TaeHagen** [comment]
Fixed in-app, pending release.
