### ISSUE TITLE
Send and Receive Sounds

### ISSUE THREAD

**Issue by JemsGems** [TaeHagen/bluebubbles-app#22]
Send and receive sounds don't seem to work. When I add send and receive sounds in Conversation Settings, they don't play when I send a message and glitch out a little when playing the preview of the sound.

**Comment by kymerea** [comment]
This is an upstream issue (Bluebubbles issue) not an openbubbles issue.

**Comment by JemsGems** [comment]
Yeah but it works on BlueBubbles and not OB

**Comment by TaeHagen** [comment]
Fixed upstream with rebase.
