### ISSUE TITLE
Change how renewal time is presented to the user

### ISSUE THREAD

**Issue by CloudRealm** [TaeHagen/bluebubbles-app#23]
The way renew time (renewal time sounds better) is shown in the app is pretty ambiguous.
It doesn't differentiate between how registration is different on Mac vs iPhone.(as far as i understand it, it is, maybe im misunderstanding how this works)
It also does not mention how Apple can make the device re-register at anytime.
It can be shown in a more informative way.

**Comment by TaeHagen** [comment]
How would you suggest fixing this? I don't want to insert a whole explainer there

**Comment by CloudRealm** [comment]
I can think of a couple of options.

Option 1: make the renew time clickable/add a dropdown and it says to view more information about renewal system visit docs and it links the docs site.

Option 2: If ob detects that a Mac hardware code wasn't used in set up, add something to the profile that says apple can force a renew at any time. ( Or something like that)

**Comment by TaeHagen** [comment]
A good enhancement would be to notify users when re-registration fails. However, that is covered by #3 

This won't be fixed.
