### ISSUE TITLE
Large attachments crash the app / dont show file size limit

### ISSUE THREAD

**Issue by CloudRealm** [TaeHagen/bluebubbles-app#24]
Files bigger than 1 GB(like 1.2GB)  crash the app when attempting to send them. 
They also do not show the 1gb file size limit message.

Only files a little bit over 1gb show the file size limit message.
This may be due to how OpenBubbles calculates file sizes.

**Comment by CloudRealm** [comment]
https://github.com/TaeHagen/bluebubbles-app/issues/25

**Comment by kymerea** [comment]
Upstream issue - So it's a bluebubbles issue and not an open-bubbles issue.

**Comment by CloudRealm** [comment]
> Upstream issue - So it's a bluebubbles issue and not an open-bubbles issue.

for both issues? or just one?

**Comment by TaeHagen** [comment]
Upstream bug - not handled by OpenBubbles.

It will attempt to send as large as file as it can.
