### ISSUE TITLE
OpenBubbles does not correctly calculate file sizes

### ISSUE THREAD

**Issue by CloudRealm** [TaeHagen/bluebubbles-app#25]
OpenBubbles does not calculate file sizes correctly.

![Screenshot_20240830-170814](https://github.com/user-attachments/assets/bc002e2b-f7f3-4f57-8b59-8e9a08846fff)
![Screenshot_20240830-1700092](https://github.com/user-attachments/assets/9cd5bab6-abc5-4263-825c-138eacb36f94)

**Comment by TaeHagen** [comment]
Upstream issue - please post to BB. Yes the byte calculation is wonky. This is not a significant issue.
