### ISSUE TITLE
Storage permission error

### ISSUE THREAD

**Issue by Baggette** [TaeHagen/bluebubbles-app#28]
The app is unable to access any files on the device even though it has the permissions to do so. I have tried clearing app cache, clearing app data, resetting up the entire setup and reinstalling however none solved the issue. If it matters I do not have this issue with bluebubbles (the phone app) and its a rooted s9 with android 10 (stock rom)

https://github.com/user-attachments/assets/6698613a-b41c-42bd-ac5f-656166649cc4

**Comment by Baggette** [comment]
If I can provide any other information please let me know

**Comment by TaeHagen** [comment]
Are you still experiencing this on the latest update?

**Comment by Baggette** [comment]
> Are you still experiencing this on the latest update?

I honestly haven't used the app for a while as rcs has been added to iphones and I mostly get rcs from alot of my friends now, however Ill try and see if the openbubbles app still has the issue and get back to you

**Comment by Baggette** [comment]
clicked the wrong button whoops

**Comment by cameronaaron** [comment]
Seems like this can be closed?

**Comment by Baggette** [comment]
> Seems like this can be closed?

Yes, i just tested and the issue is no longer present, my apologies for taking so long to test it, I've been busy.
