### ISSUE TITLE
Empty messages carrying over from SMS

### ISSUE THREAD

**Issue by fl3xtra** [TaeHagen/bluebubbles-app#29]
Messages from SMS will carry over into OB that are empty.

**Comment by TaeHagen** [comment]
To be clear, this is with SMS forwarding disabled in Settings -> Profile?

**Comment by fl3xtra** [comment]
Correct. Screenshots attached.

![Screenshot_20240921-131200](https://github.com/user-attachments/assets/51933ffa-5559-4c17-9090-c48b3c79f7dd)
![Screenshot_20240921-131212](https://github.com/user-attachments/assets/e135d009-729a-46c2-a55e-419984d87e3f)

**Comment by fl3xtra** [comment]
Correct

![Screenshot_20240921-131200](https://github.com/user-attachments/assets/0fc7d9fe-65de-4bc2-9dd7-c02b9cea7edd)
![Screenshot_20240921-131212](https://github.com/user-attachments/assets/7e19fce2-f191-477a-aac7-4b4b748bfabe)

**Comment by TaeHagen** [comment]
Fixed, already released.
