### ISSUE TITLE
Duplicate chats

### ISSUE THREAD

**Issue by Baggette** [TaeHagen/bluebubbles-app#31]
When receiving a message from someone, if they sent an sms message and a iMessage message they show up as two separate chats instead of being one chat that had a sms messages and then an Imessage message. 
Maybe this is an intended "feature"? but it seems kinda clunky and weird 

once more if I can provide more information or logs please let me know

**Comment by TaeHagen** [comment]
This is an upstream BlueBubbles issue. Please file in their issue tracker:
https://github.com/BlueBubblesApp/bluebubbles-app/issues
