### ISSUE TITLE
Chat list preview doesn't show stickers properly 

### ISSUE THREAD

**Issue by CloudRealm** [TaeHagen/bluebubbles-app#32]
![Screenshot_20240925-164837](https://github.com/user-attachments/assets/e298bd72-96e9-48d5-81b7-7fbc60792a50)
![Screenshot_20240925-164901](https://github.com/user-attachments/assets/65d861dd-17f8-4240-ac39-dedaaba23857)

**Comment by TaeHagen** [comment]
Fixed pending release
