### ISSUE TITLE
Message profile page shows iCloud email when using phone registration 

### ISSUE THREAD

**Issue by CloudRealm** [TaeHagen/bluebubbles-app#33]
The message profile page shows iCloud email, when no email was used.

I am using a relay code from jjtechs relay app and skipped apple id login. I suspect the app is remembering the old login from when I did login to my apple id. I am currently not logged into apple id, and cannot select any other aliases.

**Comment by cameronaaron** [comment]
I think this is just as designed your apple id is always an email address

**Comment by TaeHagen** [comment]
Fixed pending release
