### ISSUE TITLE
Android app won't accept inputing code on hardware info screen

### ISSUE THREAD

**Issue by brekker23** [TaeHagen/bluebubbles-app#34]
The android app won't accept me inputting my hardware code manually. I'm trying to use the UDID from my iPhone rather than a mac, but when I put in the code, there is no way for me to submit it. There is no enter button or submit button, it just sits there looking sad and doing nothing

**Comment by cameronaaron** [comment]
are you sure you are adding the dashes in the code? Are you using the code from validation relay made by jjtech?

**Comment by TaeHagen** [comment]
It cannot work with simply a UDID. It will auto-submit when it has a valid hardware or relay code.
