### ISSUE TITLE
"Error registering with IDS: 6001" - Unable to sign in after disabling both ADP & Security Keys

### ISSUE THREAD

**Issue by flopsiedev** [TaeHagen/bluebubbles-app#36]
I was having issues with the sign-in process with my Apple ID. I thought it was ADP since some people complained of this, so I went forward with disabling it. Then I realized it made more sense that Security keys were the issue, and proceeded to remove those too.
The sign in process was going as expected and prompted a 2FA code accordingly, until all I got was an, "Error registering with IDS: 6001" and now I can't even get to the 2FA setup cause after inputting my email and password, I just get that same error. Can't find any info on it online, only seeing reddit threads related to IRS stuff, and no issues open or closed afaik.

![image](https://github.com/user-attachments/assets/0b24d300-a8ac-44af-b24c-5b7694cf016f)

**Comment by cameronaaron** [comment]
When the next version drops in the next few days give it a try

**Comment by TaeHagen** [comment]
Does this issue persist on the new release?

**Comment by cameronaaron** [comment]
I kinda doubt it would

**Comment by flopsiedev** [comment]
Issue still persists as of 6:21PM Central. :(

**Comment by TaeHagen** [comment]
Can you DM me on Discord? User: Copperboy100

I would ordinarily ask for logs, but given you can't log in it will require a bit extra setup to get them

**Comment by TaeHagen** [comment]
This is caused by Contact Key Verification not being supported.

An in-app reminder has been added.

**Comment by flopsiedev** [comment]
Can confirm, and it helped me understand how CKV works too~
![image](https://github.com/user-attachments/assets/32a918cc-f444-437a-88dc-ecc18398eb3c)
