### ISSUE TITLE
If the keyboard is open, when I scroll down in a chat, the keyboard should be dismissed 

### ISSUE THREAD

**Issue by ericmigi** [TaeHagen/bluebubbles-app#40]
Like in Whatsapp/Google messages

**Comment by TaeHagen** [comment]
I don't have Google messages but I have WhatsApp and it's not doing this? Neither does Discord?

**Comment by ericmigi** [comment]
Ah you're right! I haven't used Whatsapp in a while. But GM and beeper do it

**Comment by TaeHagen** [comment]
Already supported, enable in settings under conversion settings
