### ISSUE TITLE
auto download media isn't working reliably

### ISSUE THREAD

**Issue by ericmigi** [TaeHagen/bluebubbles-app#45]
auto download media didn't work with this movie. I had to tap on it to get it to download, despite the setting being on ![Screenshot_20241125-055957.png](https://github.com/user-attachments/assets/a9167ff5-0858-4873-aff4-9f2ed292b882)

I sent logs privately

**Comment by cameronaaron** [comment]
@ericmigi Quick question is this only happening for one movie/video or for all?

**Comment by ericmigi** [comment]
@TaeHagen is on this one
