### ISSUE TITLE
Search doesn't return chats, only messages 

### ISSUE THREAD

**Issue by ericmigi** [TaeHagen/bluebubbles-app#49]
![Screenshot_20241129-092801~2.png](https://github.com/user-attachments/assets/c163f12b-7692-46e0-ae31-9f5096469516)

![Screenshot_20241129-092750.png](https://github.com/user-attachments/assets/c26c4748-6552-41d4-bc09-3afa803516ed)

**Comment by TaeHagen** [comment]
Fixed pending release

**Comment by ericmigi** [comment]
When is this one rolling out?
