### ISSUE TITLE
reregistering requires a relogin

### ISSUE THREAD

**Issue by crashbandicode** [TaeHagen/bluebubbles-app#51]
Im using an iPhone 6 with checkra1n and when the phone deregisters it doesn't auto reregister. At some point when using the app it logs me out and I have to re login with my apple credentials. Also after logging it open bubbles gets stuck on the login page and I have to close the app and reopen to see my messages again. Not only this but ever message received then says unverified and I'm not able to send messages from my iPhone but I can from my Mac. It's like open bubbles successfully logs in and reregisters with manual intervention but I'm unable to send messages out from the iPhone. 

I can provide more details, logs etc if needed. I can also break this up into separate issues if desired as there are a few things going on.

**Comment by crashbandicode** [comment]
Just an update. I was able to fix most of the issue by signing out of my apple account on the iPhone with the relay. I believe this is mentioned in the documentation. I am still unable to send messages though even after clearing the identity cache.

**Comment by TaeHagen** [comment]
The sending messages can take a bit. You do need to log out on the iPhone. It will not log you out if re-registration fails, only if Apple logs you out on their end. If re-registration fails sending messages will simply fail. Status is visible in profile section.
