### ISSUE TITLE
iPad 8th Gen wifi issues

### ISSUE THREAD

**Issue by CloudRealm** [TaeHagen/bluebubbles-app#6]
- OpenBubbles seems to not work at all with the iPad 8th gen
 -  iMessage doesnt send msgs / no phone number reg
 App gives no error messages unless I click reregister and then it gives me this error
![image](https://github.com/user-attachments/assets/f0166195-cbda-4a3b-be90-61589fe26b08)

**Comment by JJTech0130** [comment]
Support for the iPad should be somewhat fixed in the latest release, if you still have issues with phone number registration using it should be folded into #4
