### ISSUE TITLE
Phone number deregistered after 20 min 

### ISSUE THREAD

**Issue by cameronaaron** [TaeHagen/bluebubbles-app#9]
My phone number was deregistered after 20 mins the logs said this. Everything seems fine with the validation data device the code is the same etc

WARN [rustpush::imessage::identity_manager] No public key for token retry false .
ERROR [rustpush::imessage::aps_client] No identity for payload! Do not retry IDS key missing for tel:+1 .
ERROR [rust_lib_bluebubbles::api::api] Do not retry IDS key missing for tel:+1 .
DEBUG [rustls::common_state] Sending warning alert CloseNotify .
DEBUG [rustls::client::hs] No cached session for DnsName("albert.apple.com") .

**Comment by cameronaaron** [comment]
Screenshot and logs sent to copperboy

**Comment by TaeHagen** [comment]
No longer has issue, check OB status in settings and DM if experiencing
